# This is your secrets file.
# Replace the placeholder with your actual Google AI Studio API key.

GOOGLE_API_KEY = "AIzaSyCajA-t68BWLwRSrc3qolSBNRGw70xMnzo"

# The URL for your local Qdrant instance.
# You likely don't need to change this.
QDRANT_URL = "http://localhost:6333"